/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Issa (https://sketchfab.com/holdmydrink)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-and-clean-piggybank-optional-side-logo-40dd69fd5091499cb4c22dc84afcbe40
Title: Cute and Clean Piggybank (optional side logo)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Floor} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.eyes} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.gold1} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.logo1} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
